# Generated by Django 5.1 on 2025-02-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_price", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsmeli",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
