# Generated by Django 5.1 on 2024-09-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainproducts",
            name="image_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
