# Generated by Django 5.1 on 2025-02-24 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_price", "0002_productsmeli_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="melonn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("stock", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "main_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_price.mainproducts",
                        verbose_name="main_product",
                    ),
                ),
            ],
        ),
    ]
