# Generated by Django 5.1 on 2024-10-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0002_mainproducts_image_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainproducts",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="sopifyproducts",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sopifyproducts",
            name="cursor",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="sopifyproducts",
            name="inventory_quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="sopifyproducts",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sopifyproducts",
            name="tags",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="sopifyproducts",
            name="vendor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
