# Generated by Django 5.1 on 2024-10-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0003_mainproducts_title_sopifyproducts_barcode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sopifyproducts",
            name="inventory_quantity",
        ),
        migrations.AddField(
            model_name="mainproducts",
            name="inventory_quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="sopifyproducts",
            name="category",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
