# Generated by Django 5.1 on 2025-02-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_price", "0003_melonn"),
    ]

    operations = [
        migrations.AddField(
            model_name="melonn",
            name="sku",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
