# Generated by Django 5.1 on 2024-10-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0004_remove_sopifyproducts_inventory_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainproducts",
            name="id_product",
            field=models.CharField(max_length=300),
        ),
    ]
