# Generated by Django 5.1 on 2024-08-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0004_alter_oauthtoken_refresh_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthtoken",
            name="refresh_token",
            field=models.TextField(),
        ),
    ]
