# Generated by Django 5.1 on 2025-02-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_price", "0004_melonn_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="melonn",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
