# Generated by Django 5.1 on 2024-10-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0005_alter_mainproducts_id_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainproducts",
            name="items_number",
            field=models.IntegerField(default=1),
        ),
    ]
