# Generated by Django 5.1 on 2024-08-24 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0005_alter_oauthtoken_refresh_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oauthtoken",
            name="user",
        ),
    ]
