# Generated by Django 5.1 on 2025-02-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_price", "0005_alter_melonn_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainproducts",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
