# Generated by Django 5.1 on 2024-08-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0006_remove_oauthtoken_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsmeli",
            name="crossed_out_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="productsmeli",
            name="free_shipping",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productsmeli",
            name="link",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="productsmeli",
            name="local_pick_up",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productsmeli",
            name="shipment_cost",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="productsmeli",
            name="store_pick_up",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productsmeli",
            name="weight",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
