# Generated by Django 5.1 on 2024-10-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0006_alter_mainproducts_items_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sopifyproducts",
            old_name="price",
            new_name="real_price",
        ),
        migrations.AddField(
            model_name="sopifyproducts",
            name="projected_compare_at_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="sopifyproducts",
            name="projected_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
