# Generated by Django 5.1 on 2024-08-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0007_productsmeli_crossed_out_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsmeli",
            name="logistic_type",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="productsmeli",
            name="weight",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
