# Generated by Django 5.1 on 2024-08-27 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0008_productsmeli_logistic_type_alter_productsmeli_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsmeli",
            name="main_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master_price.mainproducts",
                verbose_name="main_product",
            ),
        ),
        migrations.AlterField(
            model_name="productssodimac",
            name="main_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master_price.mainproducts",
                verbose_name="main_product",
            ),
        ),
    ]
