# Generated by Django 5.1 on 2024-10-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0009_productsmeli_projected_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productsmeli",
            old_name="main_product",
            new_name="MainProducts",
        ),
        migrations.RenameField(
            model_name="productssodimac",
            old_name="main_product",
            new_name="MainProducts",
        ),
        migrations.AddField(
            model_name="productssodimac",
            name="guide",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="productssodimac",
            name="pricePublication",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="mainproducts",
            name="commission_seller",
            field=models.FloatField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name="mainproducts",
            name="publicity",
            field=models.FloatField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name="mainproducts",
            name="utility",
            field=models.FloatField(blank=True, default=18, null=True),
        ),
    ]
