# Generated by Django 5.1 on 2024-08-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0009_alter_productsmeli_main_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsmeli",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
