# Generated by Django 5.1 on 2024-10-12 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0010_rename_main_product_productsmeli_mainproducts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sopifyproducts",
            name="cursor",
        ),
    ]
