# Generated by Django 5.1 on 2024-08-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0010_productsmeli_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsmeli",
            name="image_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
