# Generated by Django 5.1 on 2024-08-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0011_productsmeli_image_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsmeli",
            name="image_link",
        ),
        migrations.AddField(
            model_name="mainproducts",
            name="image_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
