# Generated by Django 5.1 on 2024-10-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0011_remove_sopifyproducts_cursor"),
    ]

    operations = [
        migrations.AddField(
            model_name="sopifyproducts",
            name="margen",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
