# Generated by Django 5.1 on 2025-01-20 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0012_sopifyproducts_margen"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductsMelonn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "internalCode",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "inventory_quantity",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "MainProducts",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_price.mainproducts",
                        verbose_name="main_product",
                    ),
                ),
            ],
        ),
    ]
