# Generated by Django 5.1 on 2024-09-09 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0012_remove_productsmeli_image_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="packaging_cost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_cost", models.FloatField(blank=True, default=0, null=True)),
                ("piece_cost", models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="mainproducts",
            name="margen",
        ),
        migrations.AddField(
            model_name="mainproducts",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mainproducts",
            name="items_number",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PriceEngine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("margen", models.FloatField(blank=True, default=0, null=True)),
                (
                    "commission_seller",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "commission_platform",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("shipping", models.FloatField(blank=True, default=0, null=True)),
                ("publicity", models.FloatField(blank=True, default=0, null=True)),
                ("aditional", models.FloatField(blank=True, default=0, null=True)),
                (
                    "main_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_price.mainproducts",
                        verbose_name="main_product",
                    ),
                ),
            ],
        ),
    ]
