# Generated by Django 5.1 on 2025-01-30 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0013_productsmelonn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainproducts",
            name="inventory_quantity",
        ),
    ]
