# Generated by Django 5.1 on 2024-09-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0013_packaging_cost_remove_mainproducts_margen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainproducts",
            name="category",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
