# Generated by Django 5.1 on 2025-01-31 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0014_remove_mainproducts_inventory_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainproducts",
            name="price_base",
        ),
        migrations.CreateModel(
            name="ProductsFalabella",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ShopSku",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("Url", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "MainProducts",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_price.mainproducts",
                        verbose_name="main_product",
                    ),
                ),
            ],
        ),
    ]
