# Generated by Django 5.1 on 2024-09-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_price", "0014_alter_mainproducts_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainproducts",
            name="category",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
